apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- toYaml .Values.homeAssistant.configurations | nindent 2 }}
