apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  secrets.yaml: |
    {{- .Values.homeAssistant.secrets | nindent 4 }}